-- Batch 2: Utah, Georgia, Arizona vendors
-- Run after initial seed

-- =====================================================
-- UTAH
-- =====================================================

INSERT INTO vendors (name, slug, description, short_description, phone, email, website, address, city, state, zip, latitude, longitude, sport_types, service_types, service_area_miles, tier, is_verified, is_featured, rating, review_count, years_in_business, license_number, insurance_verified, logo_url, gallery_urls)
VALUES (
  'Precision Pro Courts',
  'precision-pro-courts',
  'Precision Pro Courts specializes in creating and resurfacing athletic courts across Utah. From backyard courts to municipal parks, they deliver exceptional craftsmanship and service. They proudly serve Utah County, Salt Lake County, Davis County, Weber County, Juab County, and Washington County with pickleball, tennis, basketball, and multi-sport court solutions.',
  'Utah''s premier court experts for pickleball, tennis, basketball construction and resurfacing.',
  '',
  '',
  'https://precisionprocourts.com',
  '',
  'Salt Lake City',
  'UT',
  '84101',
  40.7608,
  -111.8910,
  '{pickleball,tennis,basketball,multi-sport}',
  '{new-construction,resurfacing,design}',
  150,
  'free',
  false,
  false,
  0,
  0,
  5,
  NULL,
  false,
  NULL,
  '{}'
);

INSERT INTO vendors (name, slug, description, short_description, phone, email, website, address, city, state, zip, latitude, longitude, sport_types, service_types, service_area_miles, tier, is_verified, is_featured, rating, review_count, years_in_business, license_number, insurance_verified, logo_url, gallery_urls)
VALUES (
  'Courts Unlimited',
  'courts-unlimited-utah',
  'Courts Unlimited offers high-quality residential tennis, pickleball and basketball court construction and surfacing throughout the state of Utah. With over 30 years of experience and 3,000+ courts surfaced, owner Mike Wren and his team specialize in post-tension concrete courts, resurfacing, and crack repair. They serve Utah, Idaho, Wyoming, and Nevada.',
  'Utah industry leader in court construction with 30+ years experience and 3,000+ courts surfaced.',
  '',
  '',
  'https://courtsunlimitedut.com',
  '',
  'Salt Lake City',
  'UT',
  '84101',
  40.7608,
  -111.8910,
  '{tennis,pickleball,basketball,multi-sport}',
  '{new-construction,resurfacing,repair,maintenance,lighting,fencing,design}',
  300,
  'free',
  false,
  false,
  0,
  0,
  30,
  NULL,
  false,
  NULL,
  '{}'
);

INSERT INTO vendors (name, slug, description, short_description, phone, email, website, address, city, state, zip, latitude, longitude, sport_types, service_types, service_area_miles, tier, is_verified, is_featured, rating, review_count, years_in_business, license_number, insurance_verified, logo_url, gallery_urls)
VALUES (
  'Parkin Tennis Courts',
  'parkin-tennis-courts',
  'Parkin Tennis Courts is a tennis, basketball and pickleball court builder specializing in post-tension concrete courts. One of only a small handful of contractors in the western United States certified to perform post-tension work. They handle all excavation, concrete, fencing, landscaping, and construction — a full general contracting firm that specializes in high quality courts.',
  'Utah''s certified post-tension concrete court specialist for tennis, basketball, and pickleball.',
  '',
  '',
  'https://www.parkintennis.com',
  '',
  'Salt Lake City',
  'UT',
  '84101',
  40.7608,
  -111.8910,
  '{tennis,pickleball,basketball}',
  '{new-construction,resurfacing,repair,fencing,design}',
  150,
  'free',
  false,
  false,
  0,
  0,
  47,
  NULL,
  false,
  NULL,
  '{}'
);

INSERT INTO vendors (name, slug, description, short_description, phone, email, website, address, city, state, zip, latitude, longitude, sport_types, service_types, service_area_miles, tier, is_verified, is_featured, rating, review_count, years_in_business, license_number, insurance_verified, logo_url, gallery_urls)
VALUES (
  'Ace Courts',
  'ace-courts-utah',
  'For 30 years, Ace Courts has been Utah''s trusted name in court construction. They proudly serve the entire state, from Cache Valley and Garden City to St. George, Cedar City, Salt Lake City, Heber City, Park City, Layton, Alpine, and beyond. They build top-quality pickleball, basketball, and tennis courts with a commitment to exceptional craftsmanship.',
  'Utah''s trusted court builder for 30 years. Pickleball, basketball, and tennis statewide.',
  '',
  '',
  'https://www.acecourtsutah.com',
  '',
  'Provo',
  'UT',
  '84601',
  40.2338,
  -111.6585,
  '{pickleball,basketball,tennis,multi-sport}',
  '{new-construction,resurfacing,repair}',
  200,
  'free',
  false,
  false,
  0,
  0,
  30,
  NULL,
  false,
  NULL,
  '{}'
);

INSERT INTO vendors (name, slug, description, short_description, phone, email, website, address, city, state, zip, latitude, longitude, sport_types, service_types, service_area_miles, tier, is_verified, is_featured, rating, review_count, years_in_business, license_number, insurance_verified, logo_url, gallery_urls)
VALUES (
  'SportsWest Construction',
  'sportswest-construction',
  'SportsWest Construction is the official Sport Court builder serving Utah since 1974. With over 40 years of experience, they specialize in basketball courts, tennis courts, pickleball courts, volleyball courts, and more. As the exclusive Sport Court dealer, they have access to the leading modular sports surfaces. They serve the entire state of Utah with customized solutions for residential and commercial clients.',
  'Official Sport Court builder serving Utah since 1974. 40+ years of sports construction excellence.',
  '',
  '',
  'https://www.sportswestco.com',
  '',
  'Salt Lake City',
  'UT',
  '84101',
  40.7608,
  -111.8910,
  '{basketball,tennis,pickleball,volleyball,multi-sport}',
  '{new-construction,resurfacing,repair,design}',
  300,
  'free',
  false,
  false,
  0,
  0,
  51,
  NULL,
  false,
  NULL,
  '{}'
);

-- =====================================================
-- GEORGIA
-- =====================================================

INSERT INTO vendors (name, slug, description, short_description, phone, email, website, address, city, state, zip, latitude, longitude, sport_types, service_types, service_area_miles, tier, is_verified, is_featured, rating, review_count, years_in_business, license_number, insurance_verified, logo_url, gallery_urls)
VALUES (
  'GA Sports Construction',
  'ga-sports-construction',
  'GA Sports Construction is a General Acrylics Company since 1958. They specialize in tennis courts, pickleball courts, basketball and multi-purpose courts, bocce courts, running tracks, and synthetic turf fields. Winner of numerous national ASBA awards for 13 consecutive years with certified Tennis Court and Track Builders on staff. Experts in design-build for projects of any size.',
  'Award-winning sports construction company since 1958. Tennis, pickleball, tracks, and turf in Georgia.',
  '',
  '',
  'https://www.gasports.com',
  '',
  'Atlanta',
  'GA',
  '30301',
  33.7490,
  -84.3880,
  '{tennis,pickleball,basketball,track,soccer,football,multi-sport}',
  '{new-construction,resurfacing,repair,design,consulting}',
  300,
  'free',
  false,
  false,
  0,
  0,
  67,
  NULL,
  false,
  NULL,
  '{}'
);

INSERT INTO vendors (name, slug, description, short_description, phone, email, website, address, city, state, zip, latitude, longitude, sport_types, service_types, service_area_miles, tier, is_verified, is_featured, rating, review_count, years_in_business, license_number, insurance_verified, logo_url, gallery_urls)
VALUES (
  'Court Makers',
  'court-makers-georgia',
  'Court Makers Inc. has been based outside of Atlanta in Marietta, GA since 1976. They''ve installed and resurfaced thousands of tennis courts and pickleball courts throughout the Southeast, working with the South''s most prestigious clients. ASBA Certified Tennis Court Builder on staff. Members of the Cobb Chamber of Commerce, Atlanta Apartment Association, and Georgia Home Builders Association.',
  'Atlanta''s premier tennis and pickleball court builder since 1976. ASBA certified, 150,000+ satisfied customers.',
  '(770) 795-8400',
  '',
  'https://courtmakers.com',
  '',
  'Marietta',
  'GA',
  '30060',
  33.9526,
  -84.5499,
  '{tennis,pickleball,multi-sport}',
  '{new-construction,resurfacing,repair,maintenance,lighting,equipment}',
  200,
  'free',
  false,
  false,
  0,
  0,
  49,
  NULL,
  false,
  NULL,
  '{}'
);

INSERT INTO vendors (name, slug, description, short_description, phone, email, website, address, city, state, zip, latitude, longitude, sport_types, service_types, service_area_miles, tier, is_verified, is_featured, rating, review_count, years_in_business, license_number, insurance_verified, logo_url, gallery_urls)
VALUES (
  'CBA Sports',
  'cba-sports-georgia',
  'CBA Sports has been constructing outdoor court systems for over 30 years. They are the official Sport Court dealer in Georgia, specializing in basketball, tennis, pickleball, and futsal court installation. Fully licensed, insured, and bonded with dedicated project managers. Their interactive court builder helps clients visualize projects before construction begins.',
  'Official Sport Court dealer in Georgia with 30+ years of outdoor court construction experience.',
  '',
  '',
  'https://www.cbasports.com',
  '',
  'Buford',
  'GA',
  '30518',
  34.1207,
  -84.0043,
  '{basketball,tennis,pickleball,volleyball,multi-sport}',
  '{new-construction,resurfacing,repair,design,lighting,fencing}',
  200,
  'free',
  false,
  false,
  0,
  0,
  30,
  NULL,
  false,
  NULL,
  '{}'
);

INSERT INTO vendors (name, slug, description, short_description, phone, email, website, address, city, state, zip, latitude, longitude, sport_types, service_types, service_area_miles, tier, is_verified, is_featured, rating, review_count, years_in_business, license_number, insurance_verified, logo_url, gallery_urls)
VALUES (
  'Match Point Tennis',
  'match-point-tennis-georgia',
  'Match Point Tennis provides full-service sports court solutions in Georgia and the Southeast. They specialize in new construction, resurfacing, rebuilding, and Riteway crack repair for tennis and pickleball courts. Known for precision craftsmanship and superior materials, they serve sports facility owners, municipalities, schools, and residential clients.',
  'Full-service tennis and pickleball court construction and resurfacing experts in Georgia.',
  '',
  '',
  'https://matchpointtennis.info',
  '',
  'Atlanta',
  'GA',
  '30301',
  33.7490,
  -84.3880,
  '{tennis,pickleball,basketball}',
  '{new-construction,resurfacing,repair,lighting,equipment}',
  200,
  'free',
  false,
  false,
  0,
  0,
  10,
  NULL,
  false,
  NULL,
  '{}'
);

-- =====================================================
-- ARIZONA
-- =====================================================

INSERT INTO vendors (name, slug, description, short_description, phone, email, website, address, city, state, zip, latitude, longitude, sport_types, service_types, service_area_miles, tier, is_verified, is_featured, rating, review_count, years_in_business, license_number, insurance_verified, logo_url, gallery_urls)
VALUES (
  'Apex Court Builders',
  'apex-court-builders-arizona',
  'Apex Court Builders of Arizona is a family-owned and operated business with forty years in the industry. They specialize in statewide construction, resurfacing, and repair of tennis courts, pickleball courts, basketball courts, bocce courts, playgrounds, and running tracks. Serving Phoenix, Tucson, Yuma, Prescott, and throughout Arizona. ASBA member and BBB accredited.',
  'Family-owned Arizona court builder with 40 years experience. Tennis, pickleball, basketball, and tracks.',
  '',
  '',
  'https://apexcourtbuilders.com',
  '',
  'Tempe',
  'AZ',
  '85281',
  33.4255,
  -111.9400,
  '{tennis,pickleball,basketball,track,multi-sport}',
  '{new-construction,resurfacing,repair}',
  300,
  'free',
  false,
  false,
  0,
  0,
  40,
  NULL,
  false,
  NULL,
  '{}'
);

INSERT INTO vendors (name, slug, description, short_description, phone, email, website, address, city, state, zip, latitude, longitude, sport_types, service_types, service_area_miles, tier, is_verified, is_featured, rating, review_count, years_in_business, license_number, insurance_verified, logo_url, gallery_urls)
VALUES (
  'PAC Tennis AZ',
  'pac-tennis-az',
  'For more than four decades, PAC Tennis AZ has been the trusted name in court construction and resurfacing in Arizona. Their expertise, craftsmanship, and commitment to quality have made them the premier choice for building, resurfacing, and maintaining high-performance tennis, pickleball, and multi-sport courts for schools, cities, athletic clubs, and homeowners.',
  'Arizona''s trusted court construction and resurfacing experts for 40+ years.',
  '',
  '',
  'https://pactennisaz.com',
  '',
  'Phoenix',
  'AZ',
  '85001',
  33.4484,
  -112.0740,
  '{tennis,pickleball,basketball,multi-sport}',
  '{new-construction,resurfacing,repair}',
  250,
  'free',
  false,
  false,
  0,
  0,
  40,
  NULL,
  false,
  NULL,
  '{}'
);

INSERT INTO vendors (name, slug, description, short_description, phone, email, website, address, city, state, zip, latitude, longitude, sport_types, service_types, service_area_miles, tier, is_verified, is_featured, rating, review_count, years_in_business, license_number, insurance_verified, logo_url, gallery_urls)
VALUES (
  'Sport Court of Arizona',
  'sport-court-arizona',
  'Sport Court of Arizona has been building custom, premium quality game courts for residential and commercial properties for nearly 50 years. A local, family-owned business offering Sport Court modular flooring and post-tensioned courts with latex acrylic finishes. From backyard basketball to tennis and pickleball clubs, they serve communities across the entire state.',
  'Official Sport Court builder in Arizona for nearly 50 years. Family-owned, premium quality courts.',
  '',
  '',
  'https://sportcourtaz.com',
  '',
  'Scottsdale',
  'AZ',
  '85251',
  33.4942,
  -111.9261,
  '{basketball,tennis,pickleball,volleyball,multi-sport}',
  '{new-construction,resurfacing,repair,design}',
  250,
  'free',
  false,
  false,
  0,
  0,
  50,
  NULL,
  false,
  NULL,
  '{}'
);

INSERT INTO vendors (name, slug, description, short_description, phone, email, website, address, city, state, zip, latitude, longitude, sport_types, service_types, service_area_miles, tier, is_verified, is_featured, rating, review_count, years_in_business, license_number, insurance_verified, logo_url, gallery_urls)
VALUES (
  'Phoenix Court Builders',
  'phoenix-court-builders',
  'Phoenix Court Builders is Arizona''s go-to team for backyard and commercial court construction — from pickleball and basketball to tennis and multi-courts. Fully licensed, bonded, and insured with affordable pricing and custom design. They handle grading, concrete, post-tension slabs, LED lighting, fencing, and premium UV-resistant acrylic surfacing built for Arizona heat.',
  'Arizona''s #1 pickleball court builder. Licensed, affordable, custom design for any sport.',
  '',
  '',
  'https://www.phoenixcourtbuilders.com',
  '',
  'Phoenix',
  'AZ',
  '85001',
  33.4484,
  -112.0740,
  '{pickleball,basketball,tennis,multi-sport}',
  '{new-construction,resurfacing,repair,lighting,fencing,design}',
  200,
  'free',
  false,
  false,
  0,
  0,
  5,
  NULL,
  false,
  NULL,
  '{}'
);
